name=Trilateration
version=0.1.0
author=Yersaiyn
maintainer=Yersaiyn no@email.com
sentence=SX1280 trilateration library
paragraph=Anchor/Target node logic, control protocol, and link layer for trilateration.
category=Communication
architectures=esp32
depends=RadioLib
includes=Trilateration.h
